### ISSUE TITLE
Not possible to use .trivyignore files

### ISSUE THREAD

**Issue by abstractj** [aquasecurity/trivy-action#103]
First, I would like to thank you for all the work, Trivy is a great project.

Using the command line is pretty straightforward to ignore CVEs that for some reason are false positives, or the project does not have any plans to fix like:
```
trivy --ignorefile=ignore/.trivyignore 
```

We tried to provide parameters to the Trivy action, but it seems that they don't exist:

```
....
        with:
          image-ref: ...
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'MEDIUM,CRITICAL,HIGH'
          ignore-unfixed: true
          ignorefile: ${GITHUB_WORKSPACE}/.github/ignore/.trivyignore
...
```
It is possible to provide extra-arguments, like using the `--ignorefile` parameter?
