### ISSUE TITLE
`skip-dirs` does not seem to work when specified in GHA workflow, or via environment variable

### ISSUE THREAD

**Issue by dhanakane-tw** [aquasecurity/trivy-action#108]
# Steps to replicate:

Specify a step in a workflow as follows:

```
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          skip-dirs: "foo,bar"
```

# Expected result:
Directories specified in `skip-dirs` are not scanned for vulnerabilities

# Actual result:
Directories are scanned without exclusion taking effect.

# Notes:
Supplying a comma separated string of directories using an environment variable as suggested in the cli documentation with `TRIVY_SKIP_DIRS` does not have the desired effect either.
