### ISSUE TITLE
Secret Scanning

### ISSUE THREAD

**Issue by b34rd-tek** [aquasecurity/trivy-action#109]
It appears when scanning a Git Repo using the 'fs' option, secret scanning does not occur. Is there a way to enable this within the action?

If I run trivy from cli with this command:

`trivy repo -f json -o repo.json https://github.com/chili-piper/rippling-scripts`

The resulting json file is:

```
{
  "SchemaVersion": 2,
  "ArtifactName": "https://github.com/chili-piper/rippling-scripts",
  "ArtifactType": "repository",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "MacOS/MacOS-Vanta-Agent-Install.sh",
      "Class": "secret",
      "Secrets": [
        {
          "RuleID": "aws-secret-access-key",
          "Category": "AWS",
          "Severity": "CRITICAL",
          "Title": "AWS Secret Access Key",
          "StartLine": 98,
          "EndLine": 98,
          "Match": "ser E-Mail\"\n        VANTA_KEY=*****h5m0czpmace0\" bash -"
        },
        {
          "RuleID": "aws-secret-access-key",
          "Category": "AWS",
          "Severity": "CRITICAL",
          "Title": "AWS Secret Access Key",
          "StartLine": 102,
          "EndLine": 102,
          "Match": "MAIL=$email\n        VANTA_KEY=*****h5m0czpmace0\" bash -"
        }
      ]
    }
  ]
}
```
When I run from an action setup like this:

```
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          format: 'json'
          output: 'result.json'
          exit-code: '0'
```
The resulting json file is:

```
{
  "SchemaVersion": 2,
  "ArtifactName": ".",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  }
}
```
I don't know if it makes a difference but I'm using a send email action to grab the resulting json file.

This action specifically:

`dawidd6/action-send-mail@v3`
