### ISSUE TITLE
Bug: `multiple targets cannot be specified` and `option error: option initialize error: arguments error`

### ISSUE THREAD

**Issue by HarshCasper** [aquasecurity/trivy-action#113]
## Description

I have the following workflow to implement `trivy-action`:

```yml
name: "Build Docker Images"

on:
  create: # Branch (so that the Docker image tags exist for a new branch when pushed)
          # even if nothing on 'paths' below is changed.
    branches:
      - '**'

  push:
    paths:
      - "qhub/template/image/**"
      - ".github/workflows/image.yaml"

    branches: # Only on paths above
      - '**'

    tags: # Always, regardless of paths above
      - '*'

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  jupyterlab:
    name: 'Build Docker Images'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-worker
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Lint Dockerfiles
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: ./qhub/template/image/Dockerfile.${{ matrix.dockerfile }}
          output_format: tty
          error_level: 0

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            "quansight/qhub-${{ matrix.dockerfile }}"
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Add symlink to cookiecutter dir and tree
        run: |
          cd ./qhub/template
          sudo apt-get install tree
          tree ./image

      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: "./qhub/template/image"
          file: "./qhub/template/image/Dockerfile.${{ matrix.dockerfile }}"
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ steps.meta.outputs.tags }}
            quay.io/${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: 'sarif'
          exit-code: '1'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
```

The workflow fails with the following error:

```sh
quansight/qhub-jupyterlab:sha-f02eef0" "-j ." "-k " "-l " "-m " "-n " "-o " "-p true" "-q " "-r false" "-s "
Running trivy with options:  --format  sarif --exit-code  1 --ignore-unfixed --vuln-type  os,library --severity  CRITICAL,HIGH --output  trivy-results.sarif --no-progress  quansight/qhub-jupyterlab:image-scanning
quansight/qhub-jupyterlab:sha-f02eef0
Global options:  
2022-05-[18](https://github.com/Quansight/qhub/runs/6492479890?check_suite_focus=true#step:12:19)T15:40:30.538Z	ERROR	multiple targets cannot be specified
[20](https://github.com/Quansight/qhub/runs/6492479890?check_suite_focus=true#step:12:21)22-05-18T15:40:30.538Z	FATAL	option error: option initialize error: arguments error
```

I am not able to figure out why the workflow has started failing and what I can do to possibly fix it. My primary use-case is for multiple images to be analyzed on the same runner and GitHub's CodeQL action to put up inferences where we can analyze all the issues and vulnerabilities.
