### ISSUE TITLE
Demonstrate how to use --cache-dir flag with GitHub cache action

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/trivy-action#12]
Trivy has the --cache-dir flag to point to the location where DB and image layers are cached. If we combine that with the https://github.com/actions/cache we can speed up some build jobs.

**Comment by kgeorgiou** [comment]
Hey @danielpacak - I tried to look into this and observed the following:

1. [`trivy image`](https://github.com/aquasecurity/trivy#image-1) doesn't support the `--cache-dir` flag - not sure why
2. When the `aquasec/trivy` container runs, I believe it creates `/root/.cache/trivy` **inside** the `aquasec/trivy` container. 
For `actions/cache` to cache that directory, it needs to live on the host filesystem.
Maybe this can be achieved by mounting a volume like so: `docker run --rm -v ~/.cache:/root/.cache aquasec/trivy [image-ref]`

**tl;dr**: this proved to be more complicated than I anticipated 😅

**Comment by linuxbsdfreak** [comment]
Hi @danielpacak 

I am also trying to run Trivy with Tekton based with an example 

https://github.com/lumjjb/tekton-demo/blob/master/yamls/build-img-task.yaml
https://github.com/lumjjb/tekton-demo/blob/master/yamls/update-trivy.yaml

I also see that there is no --cache-dir flag. I was wondering whether that has been removed. Would be nice to have the trivy db downloaded and image layers cached for faster scanning.

Kevin

**Comment by danielpacak** [comment]
> Hi @danielpacak
> 
> I am also trying to run Trivy with Tekton based with an example
> 
> https://github.com/lumjjb/tekton-demo/blob/master/yamls/build-img-task.yaml
> https://github.com/lumjjb/tekton-demo/blob/master/yamls/update-trivy.yaml
> 
> I also see that there is no --cache-dir flag. I was wondering whether that has been removed. Would be nice to have the trivy db downloaded and image layers cached for faster scanning.
> 
> Kevin

The `--cache-dir` flag is the global option. Check the output of `trivy -h` instead of `trivy image -h` and you'll get it. I checked Trivy v0.12.0 and it's there

**Comment by bluedigits** [comment]
@danielpacak Sadly, your answer doesn't make sense.

**Comment by bluedigits** [comment]
> > Hi @danielpacak
> > I am also trying to run Trivy with Tekton based with an example
> > https://github.com/lumjjb/tekton-demo/blob/master/yamls/build-img-task.yaml
> > https://github.com/lumjjb/tekton-demo/blob/master/yamls/update-trivy.yaml
> > I also see that there is no --cache-dir flag. I was wondering whether that has been removed. Would be nice to have the trivy db downloaded and image layers cached for faster scanning.
> > Kevin
> 
> The `--cache-dir` flag is the global option. Check the output of `trivy -h` instead of `trivy image -h` and you'll get it. I checked Trivy v0.12.0 and it's there

Sadly, that doesn't make sense. I tried `trivy-action` in our GH workflow in several versions, and indeed the `cache-dir` flag doesn't work: `Incorrect Usage: flag provided but not defined: -cache-dir`
My GH workflow step looks like this:
```
      - name: Scan branch for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          cache-dir: /tmp/.cache
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
```

**Comment by vlaurin** [comment]
@bluedigits See #50 and associated PR, that seems to resolve the error you are facing.

However, even with that fix I don't think the integration with GH actions is working, I still see the DB being downloaded on every run. I suspect the cache-dir also needs to be mounted as a volume on the Docker image which is not the case currently.

I'll try to look into this a bit more tomorrow.

**Comment by vlaurin** [comment]
Okay, got the cache to work using the fix proposed in PR #51 along with the following workflow:

**Comment by yogeshlonkar** [comment]
[aquasecurity/trivy-action@master](https://github.com/aquasecurity/trivy-action) action works with [actions/cache@v3](https://github.com/actions/cache)

I've create [trivy-cache-action](https://github.com/yogeshlonkar/trivy-cache-action) it uses GitHub's [`packages/container/{name}/version`](https://docs.github.com/en/rest/packages#get-all-package-versions-for-a-package-owned-by-an-organization) API to get latest DB SHA256 and use it for the cache key. This actions is equivalent to below steps

```yaml
- id: trivy-db
  name: Check trivy db sha
  env:
    GH_TOKEN: ${{ github.token }}
  run: |
    endpoint='/orgs/aquasecurity/packages/container/trivy-db/versions'
    headers='Accept: application/vnd.github+json'
    jqFilter='.[] | select(.metadata.container.tags[] | contains("latest")) | .name | sub("sha256:";"")'
    sha=$(gh api -H "${headers}" "${endpoint}" | jq --raw-output "${jqFilter}")
    echo "Trivy DB sha256:${sha}"
    echo "::set-output name=sha::${sha}"
- uses: actions/cache@v3
  with:
    path: .trivy
    key: ${{ runner.os }}-trivy-db-${{ steps.trivy-db.outputs.sha }}
- name: Vulnerability scan
  uses: aquasecurity/trivy-action@master
  with:
    image-ref: my-image:v1.0.0
    exit-code: '1'
    ignore-unfixed: true
    cache-dir: .trivy
- name: Fix .trivy permissions
  run: sudo chown -R $(stat . -c %u:%g) .trivy
```

@vlaurin mentioned I had to use fix the permission on the `.trivy` directory other wise you get below error

> Warning: EACCES: permission denied, scandir '/home/runner/work/\*\*\*/\*\*\*/.trivy

Maybe trivy can change the permission when downloading db so it can be easily cached?

**Comment by BretFisher** [comment]
I'd love it if GHA caching was enabled out of the box like the [Docker Build Action does it](https://docs.docker.com/build/ci/github-actions/cache/#github-cache).

**Comment by hamistao** [comment]
I am using the example workflow given [here](https://github.com/aquasecurity/trivy-action/issues/12#issuecomment-847854159) but I keep getting `chown: cannot access '.trivy': No such file or directory` in the last step of the following sequence:
```
- id: trivy-db
  name: Check trivy db sha
  env:
    GH_TOKEN: ${{ github.token }}
  run: |
    endpoint='/orgs/aquasecurity/packages/container/trivy-db/versions'
    headers='Accept: application/vnd.github+json'
    jqFilter='.[] | select(.metadata.container.tags[] | contains("latest")) | .name | sub("sha256:";"")'
    sha=$(gh api -H "${headers}" "${endpoint}" | jq --raw-output "${jqFilter}")
    echo "Trivy DB sha256:${sha}"
    echo "::set-output name=sha::${sha}"
- uses: actions/cache@v3
  with:
    path: .trivy
    key: ${{ runner.os }}-trivy-db-${{ steps.trivy-db.outputs.sha }}
- name: Vulnerability scan
  uses: aquasecurity/trivy-action@master
  with:
    image-ref: my-image:v1.0.0
    exit-code: '1'
    ignore-unfixed: true
    cache-dir: .trivy
- name: Fix .trivy permissions
  run: sudo chown -R $(stat . -c %u:%g) .trivy
```

Like the `.trivy` directory isn't created neither after que cache step an after the trivy scan. Also I never noticed the `cache-dir` being populated after the trivy workflow runs. Maybe this example assumes something previouly run or set up ow maybe I have the wrong understanding of the usage of `cache-dir`. Could someone please clarify this?
