### ISSUE TITLE
support for scanning multiple images

### ISSUE THREAD

**Issue by achton** [aquasecurity/trivy-action#130]
Not sure if this is an edge case, but I have the need for scanning multiple, dynamically-named images in a single job and failing the action if any of the images contain vulnerabilities (using `--exit-code`).

Would you be willing to accept a PR which adds that feature I can provide it? I imagine something like `--image-ref` supporting a comma-separated list of images. (Should be safe if we assume image refs cannot contain commas. 😅 )

**Comment by abhinaybyrisetty** [comment]
@achton This feature would be really good to have. 

@simar7 I would vote for option 1.

**Comment by thetredev** [comment]
+1 for either option. If 1, maybe `image-refs`?

**Comment by simar7** [comment]
We certainly welcome and PRs if you'd like to contribute. Can help review them. Let us know if you need any assistance.

**Comment by thetredev** [comment]
I'd like to, but I'm not sure how I'd test the option myself (in my fork). Can you elaborate on that?

**Comment by simar7** [comment]
> I'd like to, but I'm not sure how I'd test the option myself (in my fork). Can you elaborate on that?

you could locally run the ./entrypoint.sh script that gets called by GitHub action to try things out. for an example, take a look at the tests here https://github.com/aquasecurity/trivy-action/blob/master/test/test.bats

**Comment by jainrounak6** [comment]
I encountered a similar issue and, after extensive testing, found a solution that worked for me. Below is the code snippet that resolved the problem in my case:

```
  trivy_image_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "image1"
          - "image2"
          - "image3"

    steps:
      # Run Trivy docker image scan
      - name: Run Trivy image vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: "sarif"
          output: "trivy-${{ matrix.image }}.sarif"
          ignore-unfixed: true
          vuln-type: "os,library"
          security-checks: "vuln"

      # Upload image report to GitHub Security
      - name: Upload Trivy image scan results
        id: upload-results
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: "trivy-${{ matrix.image }}"
          sarif_file: "trivy-${{ matrix.image }}.sarif"
```

Please consider testing this in your environment and let me know if it helps. If you have any questions or if there's a more optimal solution, I'm eager to collaborate on resolving this issue.
