### ISSUE TITLE
Trivy scan action is scanning PNPM cache

### ISSUE THREAD

**Issue by imgalli** [aquasecurity/trivy-action#139]
Hi there, we're using your action and have been for some time via `@master`. Over the past few days the action is now failing due to contents of the dir `/root/.pnpm-store`.

Our config of the action is as follows, PNPM would relate to what we'd consider "application dependencies" and shouldn't be related to OS level dependencies.

```
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/XXXXXXXXXX
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
```
