### ISSUE TITLE
Add support for --dependency-tree option

### ISSUE THREAD

**Issue by rcarpio-hbo** [aquasecurity/trivy-action#140]
Using the command line it is possible to use the `--dependency-tree` to show dependency origin tree like:

```
trivy fs --dependency-tree ...
```

Reviewing the trivy-action documentation, I have seen that there is not a parameter to configure trivy to see the dependency tree.

I propose to have a new parameter to allow this.
```
....
        with:
          scan-ref: .
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'
          dependency-tree: true
....
```
