### ISSUE TITLE
Unable to pass .trivyignore file downloaded on runner to trivy action for container scan

### ISSUE THREAD

**Issue by raoganeshr** [aquasecurity/trivy-action#160]
I wanted to download a .trivyignore file on the runner before the action is called and pass that file to the action using trivyignores variable. However, it seems trivy action is unable to find the file.

What is the recommended way to pass this file other than put it inside the container image?

**Comment by simar7** [comment]
hi @raoganeshr - you could do something like this:

```
    - name: Run Trivy vulnerability scanner with trivyignore
      uses: aquasecurity/trivy-action@master
      with:
        trivyignore: /github/workspace/.trivyignore
```

**Comment by raoganeshr** [comment]
> hi @raoganeshr - you could do something like this:
> 
> ```
>     - name: Run Trivy vulnerability scanner with trivyignore
>       uses: aquasecurity/trivy-action@master
>       with:
>         trivyignore: /github/workspace/.trivyignore
> ```

tried this:

```
      - name: Download Trivy Ignore
        run: |
          curl -s https://${{ secrets.GH_TOKEN }}@raw.githubusercontent.com/Owner/workflows/main/trivy/.trivyignore -o "${{ github.workspace }}/.trivyignore"
          ls -a

        shell: bash

      - name: Scan container image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.GHCR_REPO }}/${{ inputs.image_name }}:${{ needs.build.outputs.image_tag }}"
          trivyignores: "${{ github.workspace }}/.trivyignore"
```

But it did not work. I believe it was trying to search for the file inside the container.

**Comment by raoganeshr** [comment]
@simar7 any other suggestions?

**Comment by kareemshahin** [comment]
Having the same issue when i have a `.trivyignore` in the root of my code repo.  I've tried `./`, `./.trivyignore`, `/github/workspace/.trivyignore`.

All result in the same similar error:
`ERROR: cannot find ignorefile '/github/workspace/.trivyignore'.`

here's the output of the `docker run` with the noise removed (environment variables, etc):

```
/usr/bin/docker run --name e3f2e9a96a3bad4a7fb942e6f3ac7b8c4f_e6b716 --label 5364e3 --workdir /github/workspace --rm -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/<project-repo-name>/<project-repo-name>":"/github/workspace" 5364e3:f2e9a96a3bad4a7fb942e6f3ac7b8c4f  "-a image" "-b table" "-c " "-d 1" "-e true" "-f os,library" "-g CRITICAL,HIGH" "-h " "-i <image-name>:e966e2a6c" "-j ." "-k " "-l " "-m " "-n " "-o " "-p " "-q " "-r false" "-s " "-t /github/workspace/.trivyignore" "-u " "-v "
```

The `workdir` seems to be set to `/github/workspace` and the volume seems to be mounted properly which would imply that the .trivyignore file should be present but doesn't seem to work.  Any help would be appreciated!

**Comment by drew-viles** [comment]
Hi,

I'll provide some more information on this as it's a bit of a blocker for me too.

In my scenario I'm creating a composite action that includes trivy-action to generate SBOMs for a container and then scans the container.

One particular area it's failing is the inclusion of a `trivyignore` file.

```
    - name: Scan image
      id: image-scan
      uses: aquasecurity/trivy-action@0.9.2
      with:
        image-ref: "local/${{ inputs.image-name }}:${{ inputs.image-tag }}"
        format: 'json'
        output: 'trivy-results.json'
        exit-code: ${{ inputs.scan-fail-on-detection }}
        ignore-unfixed: true
        scanners: 'vuln,secret,config'
        trivyignores: "${{ github.workspace }}/${{ inputs.trivyignore-file }}"
        severity: ${{ inputs.trivy-check-severity }}
```
As you can see from the snippet above I'm using an absolute file path. This is only because I've tried every perceivable (from my perspective of course!) variation of this and it's not working for me.

I've tried allowing the user to pass the filepath in via:
```
trivyignores: "${{ inputs.trivyignore-file }}"
```
I've tried hardcoding it - though I never expected this to work as I suspect it's looking in the action directory instead:
```
trivyignores: ".trivyignore"
```

I've even tried omitting it altogether to see if Trivy picks up the `.trivyignore` file - which again I never expect to work but it was worth a shot.

The only thing left I can think of is to have a step where by the `.trivyignore` file is copied into the location of the trivy-action. I still suspect this may not work though so any suggestions would be really appreciated.

I've looked at the entrypoint script to see how it's working but from what I can tell if a value is passed, it get catted out into a file local to the action and then that's referenced - so in theory it should be working but it's not even finding the file when it's referenced absolutely.

A bit of output for you:

![image](https://user-images.githubusercontent.com/531679/230333969-09b17655-48aa-4b69-af50-497bf87a1d67.png)


In the meantime I will keep digging into this from my side.

Thanks
