### ISSUE TITLE
fs and docker image scan doesn't return empty results the same way

### ISSUE THREAD

**Issue by jeremyhalin** [aquasecurity/trivy-action#172]
We use a workflow to do two scans, one fs, one docker image.
When the results are empty, the output isn't the same.
Is it expected behavior? It produces empty string which is weird in a comment PR.

**GitHub worflow**
```yaml
name: 'Security scans'

on:
  pull_request:
    types:
      - closed

jobs:
  scan:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test Docker image and use cache
        uses: docker/build-push-action@v3
        with:
          #file: by default load a Dockerfile with path to ./Dockerfile
          load: true
          tags: 'organization/app:${{ github.sha }}'
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy static analysis
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          output: 'trivy-fs-scan-results.output'
          security-checks: 'vuln,secret,config'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Store Trivy fs scan results in env
        run: |
          echo 'TRIVY_FS_RESULTS<<EOF' >> $GITHUB_ENV
          cat trivy-fs-scan-results.output >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Run Trivy Image Docker vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'organization/app:${{ github.sha }}'
          format: 'table'
          output: 'trivy-image-scan-results.output'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Store Trivy scan results in env
        run: |
          echo 'TRIVY_IMAGE_RESULTS<<EOF' >> $GITHUB_ENV
          cat trivy-image-scan-results.output >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Comment Trivy scan results in PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ## Trivy scan results
            
            ### fs scan
            ```
            ${{ env.TRIVY_FS_RESULTS }}
            ```
            
            ### Docker image scan
            ```
            ${{ env.TRIVY_IMAGE_RESULTS }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Screenshot of a PR comment**
![Capture d’écran 2022-10-10 160604](https://user-images.githubusercontent.com/6832672/194886744-89758848-1e2b-4d33-b580-7236c1f36da6.png)
