### ISSUE TITLE
Action starts but never finish

### ISSUE THREAD

**Issue by arxeiss** [aquasecurity/trivy-action#178]
We use Trivy in below is our Action config and it worked well till this morning. But when I created new PR, Trivy action took 27 minutes and wasn't finished still. So I canceled it and restarted it. But after 5 minutes I canceled it again, because it was stuck again.

Then I changed the code to pin the previous version `aquasecurity/trivy-action@0.7.1` and the action was finished within 10 seconds. 

<details><summary>YAML Config</summary>

```yaml
name: PR Trivy scan
on:
    pull_request:
        branches:
            - master
jobs:
    test:
        name: PR Trivy scan
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v3

            - name: Trivy config scan
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: config
                  scan-ref: .
                  skip-dirs: vendor
                  exit-code: '1'
                  severity: HIGH,CRITICAL
                  trivyignores: .trivyignore
```

</details>

This is output I see in Github Action, but it says almost nothing actually.

<details><summary>Action output</summary>

```
Run aquasecurity/trivy-action@master
  with:
    scan-type: config
    scan-ref: .
    skip-dirs: vendor
    exit-code: 1
    severity: HIGH,CRITICAL
    trivyignores: .trivyignore
    ignore-unfixed: false
    vuln-type: os,library
    format: table
    list-all-pkgs: false
/usr/bin/docker run --name d55818c38137001104dfc8921358fb0b0186b_8f7941 --label 8d5581 --workdir /github/workspace --rm -e "INPUT_SCAN-TYPE" -e "INPUT_SCAN-REF" -e "INPUT_SKIP-DIRS" -e "INPUT_EXIT-CODE" -e "INPUT_SEVERITY" -e "INPUT_TRIVYIGNORES" -e "INPUT_IMAGE-REF" -e "INPUT_INPUT" -e "INPUT_IGNORE-UNFIXED" -e "INPUT_VULN-TYPE" -e "INPUT_FORMAT" -e "INPUT_TEMPLATE" -e "INPUT_OUTPUT" -e "INPUT_SKIP-FILES" -e "INPUT_CACHE-DIR" -e "INPUT_TIMEOUT" -e "INPUT_IGNORE-POLICY" -e "INPUT_HIDE-PROGRESS" -e "INPUT_LIST-ALL-PKGS" -e "INPUT_SECURITY-CHECKS" -e "INPUT_ARTIFACT-TYPE" -e "INPUT_GITHUB-PAT" -e "INPUT_TRIVY-CONFIG" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/jarvis-proto/jarvis-proto":"/github/workspace" 8d5581:8c38137001104dfc8921358fb0b0186b  "-a config" "-b table" "-c " "-d 1" "-e false" "-f os,library" "-g HIGH,CRITICAL" "-h " "-i " "-j ." "-k vendor" "-l " "-m " "-n " "-o " "-p " "-q " "-r false" "-s " "-t .trivyignore" "-u " "-v "
Found ignorefile '.trivyignore':
# Example:
# Accept the risk
# CVE-2018-14618
CVE-2022-27664
Running trivy with options: trivy config  --format table --exit-code  1 --severity  HIGH,CRITICAL --skip-dirs vendor --ignorefile ./trivyignores .
Global options:  
2022-11-01T07:53:11.485Z	INFO	Misconfiguration scanning is enabled
Error: The operation was canceled.
```

</details>
