### ISSUE TITLE
JSON output not saved as file.

### ISSUE THREAD

**Issue by VincentPost-TomTom** [aquasecurity/trivy-action#18]
Hi, I'm having difficulties getting to the json output file. This is my workflow:

```
name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.0.7
        with:
          image-ref: 'docker.io/library/ubuntu:18.04'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '0'
      - name: test
        run: find .
      - name: test2
        run: find /
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: trivy-report
          path: trivy-report.json # or path/to/artifact
```

but the json file is not present

![image](https://user-images.githubusercontent.com/70152856/91293971-1ebdf700-e799-11ea-83f2-d77d0bebe711.png)
![image](https://user-images.githubusercontent.com/70152856/91294006-28dff580-e799-11ea-8888-82eaf43162a0.png)

What am I doing wrong here?
