### ISSUE TITLE
Option to fail only on critical CVE but also display all CVE in the table?

### ISSUE THREAD

**Issue by nat-ray** [aquasecurity/trivy-action#187]
I have the following set in my workflow: 

```
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.image_name }}:${{ env.TAG_NAME }}'
          exit: '1'
          severity: 'CRITICAL'
```

I only want the workflow to fail if a critical CVE is found. It works for my use case, but I would like it to display all CVE in my docker image (unknown,low,medium,high,critical) in the table output. Is this possible?
