### ISSUE TITLE
build privy image every run

### ISSUE THREAD

**Issue by navi86** [aquasecurity/trivy-action#193]
I see in the example https://github.com/aquasecurity/trivy-action#trivy-action
that pipeline only pull Tracy image, however when I use the same action it causes building privy docker image every run

<img width="1037" alt="Screenshot 2023-01-24 at 18 39 52" src="https://user-images.githubusercontent.com/28907696/214338765-ff8cc13c-1175-4144-acf0-71435ad8194c.png">

```
    - name: scan_docker_image_aquasec
      id: scan_docker_image_aquasec
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ needs.build_container_image.outputs.docker_image }}
        severity: "CRITICAL,HIGH"
        security-checks: vuln
        ignore-unfixed: true
        exit-code: "1"
```
what I am doing wrong ?
