### ISSUE TITLE
`skip-dirs` does not get applied

### ISSUE THREAD

**Issue by AntonOellerer** [aquasecurity/trivy-action#194]
Hey,
For [this project](https://github.com/DDS-GmbH/s3-metadata-tagger-lib/), I am trying to configure trivy to skip analyzing the `examples` folder the following way:
```yaml
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          skip-dirs: examples
```

trivy.yaml:
```yaml
format: template
template: "@/contrib/html.tpl"
exit-code: 1
severity: CRITICAL,HIGH
output: trivy-results.html
```
The directory layout of the project is so that the top level directory containes `src/` and `examples/`, with `examples` further containing a directory, in which a `package-lock.json` lies
Do you know what might be the issue here?
