### ISSUE TITLE
Action failing to scan docker images in a remote ecr after 15m with an INTERNAL_ERROR ! 

### ISSUE THREAD

**Issue by Z4ck404** [aquasecurity/trivy-action#202]
Hi, 

it worked fine for the past weeks but since the latest update, the scanner fails after 15m with the following error : 

```
image scan error: scan error: scan failed: failed analysis: analyze error: failed to analyze layer:  : walk error: failed to process the file: failed to analyze file: failed to analyze usr/local/openjdk-8/jre/lib/ext/cldrdata.jar: unable to open usr/local/openjdk-8/jre/lib/ext/cldrdata.jar: failed to open: unable to read the file: stream error: stream ID 5; INTERNAL_ERROR; received from peer

```

the scan step in my action : 

```
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '##########'
          format: 'sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
          severity: 'CRITICAL,HIGH'
          timeout: 30m0s
```
