### ISSUE TITLE
`config-policy` is not exposed

### ISSUE THREAD

**Issue by straun** [aquasecurity/trivy-action#217]
```
      - name: Run Trivy in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          config-policy: "mypolicy.rego"
```

The policies associated with other scan types are exposed.
But the policies for `config` scanning are not.
