### ISSUE TITLE
Error "unable to resolve base ref: no base refs succeeded for base: \"master\""

### ISSUE THREAD

**Issue by wenqiglantz** [aquasecurity/trivy-action#220]
I ran into the following error when I tried to run Trufflehog in my github actions workflow.  

![image](https://user-images.githubusercontent.com/13189654/224826868-d550c6a5-74d8-4e4d-9d08-02f2d6832418.png)

Here is my Trufflehog scan step in my workflow:
```
      - name: TruffleHog Secrets Scan
        uses: trufflesecurity/trufflehog@cbf299aa772f657534cd630442ddfb2f38a0f3d0
        with:
          path: ${{ inputs.working-directory }}
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
```
The "working-directory" is set to "./core" which is a directory inside my monorepo.  My default branch is named "master".

Let me know what's the root cause of the error, and how can it be fixed.  Thanks!
