### ISSUE TITLE
Upload GitHub Dependency Snapshot been skipped when passing exit-code parameter

### ISSUE THREAD

**Issue by abriko** [aquasecurity/trivy-action#232]
Workflow settings:
```
---
name: Pull Request
on:
  push:
    branches:
    - master

## GITHUB_TOKEN authentication, add only if you're not going to use a PAT
permissions:
  contents: write

jobs:
  build:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          format: 'github'
          output: 'dependency-results.sbom.json'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          image-ref: ${{ env.IMAGE_NAME }}
          github-pat: ${{ secrets.GITHUB_TOKEN }}
```
<img width="1219" alt="SCR-20230510-mrug" src="https://github.com/aquasecurity/trivy-action/assets/2601077/cfa99b90-7269-48a2-8441-f51e1688fbd8">

If remove `exit-code: '1'` we can see upload successfully.
<img width="1183" alt="SCR-20230510-mtgw" src="https://github.com/aquasecurity/trivy-action/assets/2601077/1e8a32d6-b44f-4483-9331-c8086e12d373">
