### ISSUE TITLE
The `list-all-pkgs` property in GitHub Actions does not seem to work

### ISSUE THREAD

**Issue by nipunayf** [aquasecurity/trivy-action#246]
I want to view all the JAR files discovered by Trivy Scan (`INFO JAR files found`) despite not finding any vulnerabilities. However, even though I have used the `list-all-pkgs` option as shown below, it doesn't log the JAR files.

```yaml
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          scan-ref: '.'
          format: 'json'
          list-all-pkgs: 'true'
          exit-code: '1'
```
