### ISSUE TITLE
Trivy always uploads SARIF with all levels of vulnerabilities

### ISSUE THREAD

**Issue by JakubSzuber** [aquasecurity/trivy-action#258]
The penultimate step "Run Trivy for HIGH CVEs and report" should generate the SARIF that contains only HIGH vulnerabilities because the severity is set to HIGH, but instead to GitHub Code Scanning are uploaded all levels of vulnerabilities (even LOW).

```yaml
  scan-image-Trivy:
    name: Scan Helm chart with Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Obtain permission needed for actions/checkout to fetch code
      packages: read          # Obtain permission needed to push docker image to ghcr.io
      security-events: write  # Obtain permission needed for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      # Gain an additional overview of the vulnerabilities
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: 'helm-charts/main-chart'
          exit-code: 0
          format: table

      - name: Run Trivy for all CVEs (blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: 'helm-charts/main-chart'
          exit-code: 1
          severity: 'CRITICAL'
          format: table 

      - name: Run Trivy for HIGH CVEs and report
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          scan-ref: 'helm-charts/main-chart'
          vuln-type: 'os,library'
          exit-code: 0
          ignore-unfixed: true
          severity: 'HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
```
