### ISSUE TITLE
Trivy action in SBOM mode error: Docker Action run completed with exit code 1

### ISSUE THREAD

**Issue by rblancou** [aquasecurity/trivy-action#262]
I'm using Trivy to generate SBOM of my prpject dependencies and submit them to GitHub Dependency Graph. I'm following the steps described in [Trivy documentation](https://github.com/aquasecurity/trivy-action#using-trivy-to-generate-sbom).

This is my `.yml` to configure the action:

```yaml
name: Dependency graph scanning

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Dependency graph scanning
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          trivy-config: trivy-dependency-graph.yaml
```

This is my additional Trivy configuration params:

```yaml
timeout: 10m
include-dev-deps: true
exit-code: 1
format: github
output: dependency-results.sbom.json
severity:
  - MEDIUM
  - HIGH
  - CRITICAL
scan:
  scanners:
    - vuln
    - secret
    - config
vulnerability:
  type:
    - os
    - library
  ignore-unfixed: true
```

And this is the Action result (with debug mode):
![image](https://github.com/aquasecurity/trivy-action/assets/6724744/6e66c6a3-1f5e-40e2-98d5-fbf548e3f0d1)

The Github dependency snapshot is uploaded successfully but the debug console shows the `Docker Action run completed with exit code 1` error and the Action fails. 

Why it happens?
