### ISSUE TITLE
How to use TRIVY_NON_SSL with this action?

### ISSUE THREAD

**Issue by eifinger** [aquasecurity/trivy-action#263]
I want to scan an image in a local registry which does not support https. According to the [documentation](https://github.com/aquasecurity/trivy-action#self-hosted) I used the env var `TRIVY_NON_SSL` but trivy still tries to connect via https.

Is this a bug or did I do something wrong?

I built a sample workflow to show the behavior, the failing run can be found [here](https://github.com/eifinger/actionlint-playground/actions/runs/6347762933/job/17243247516#step:5:24) and this is the config:

```yaml
---
name: Vulnerability Test
"on":
  workflow_dispatch:
jobs:
  vulnarability-test:
    name: "Run trivy on OCI image"
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Push docker image to local registry
        run: |
          docker pull ubuntu:latest
          docker tag ubuntu:latest localhost:5000/ubuntu:latest
          docker push localhost:5000/ubuntu:latest
          docker rmi ubuntu:latest localhost:5000/ubuntu:latest

      - name: Run Trivy vulnerability scanner
        continue-on-error: true
        uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f  # 0.12.0
        with:
          image-ref: "localhost:5000/ubuntu:latest"
          trivy-config: .trivy.yml
        env:
          TRIVY_NON_SSL: true
```
