### ISSUE TITLE
scan-ref doesn't work when using filesystem instead of fs

### ISSUE THREAD

**Issue by kderck** [aquasecurity/trivy-action#264]
Hello Aqua Security,  if you have a `scan-type: filesystem` instead of `scan-type: fs` the action will error with `FATAL	Require at least 1 argument` if you have specified `scan-ref: .` However, this shouldn't be a problem as `fs` is an alias of `filesystem`

```yaml
 - name: Scan Dependencies with Trivy
   uses: aquasecurity/trivy-action@master
   with:
        scan-type: filesystem
        scan-ref: .
```
