### ISSUE TITLE
Support `working_directory` input

### ISSUE THREAD

**Issue by dulltz** [aquasecurity/trivy-action#271]
## Feature Request

Support the `working_directory` optional input to change the working directory to execute Trivy.

```yaml
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          working_directory: 'foo' # ☜ like this
```

## Use Case

In a mono repo setup, scanning only specific subdirectories might be needed, especially when using `trivy-config` command. 
[tfsec-action](https://github.com/aquasecurity/tfsec-action#optional-inputs) supports `working_directory`.
Can I create a pull request to add this feature?
