### ISSUE TITLE
0.0.9 can break builds

### ISSUE THREAD

**Issue by domgraziano** [aquasecurity/trivy-action#28]
Using version 0.0.9 seems to be buggy 
```
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          docker build . --tag this_repo
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: this_repo
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
```

The `ignore-unfixed: true` will be ignored !

Tried the exact same with version 0.0.8 and it works (--ignore-unfixed is in the logs with that version)
