### ISSUE TITLE
New version 0.14.0 fails pipeline if format: 'sarif' and  exit-code: '1' and there are no CRITICAL/HIGH vulnerabilities found. 

### ISSUE THREAD

**Issue by eugentius** [aquasecurity/trivy-action#281]
New version **0.14.0** fails pipeline if `format: 'sarif'` and  `exit-code: '1'` and there are **no** CRITICAL/HIGH vulnerabilities found:
```
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ env.image-ref }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
```
Older version **0.13.1** doesn't respect `exit-code` if `format: 'sarif'`
