### ISSUE TITLE
Version 0.14.0 fails with config scan

### ISSUE THREAD

**Issue by tw-sarah** [aquasecurity/trivy-action#282]
We are using the Trivy action in our pipeline for scan-type of image and config.
We have been using `aquasecurity/trivy-action@master` and it was working fine until Nov 7.
Now, the config scan-type fails if we run with `master` or `0.14.0`. It only runs correctly if we downgrade version `0.13.1`.
(The image scan type works fine with both versions)

There are not any actual violations reported, and I can run the Trivy command on our config locally and it passes (latest version of Trivy 0.47.0). The github action turns red after a few seconds with no error reason reported. This happens in all of our Github repos.

We are running with this config:
```
      - name: Run Trivy scan on config
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          skip-dirs: 'node_modules'
```
