### ISSUE TITLE
0.14.0 is ignoring `skip-files`

### ISSUE THREAD

**Issue by nnellanspdl** [aquasecurity/trivy-action#287]
```yaml
- uses: aquasecurity/trivy-action@0.14.0
  with:
    image-ref: ${{ steps.build.outputs.image_url }}
    exit-code: '1'
    ignore-unfixed: true
    format: 'sarif'
    output: 'trivy-results.sarif'
    limit-severities-for-sarif: true
    skip-files: |
      /file1,
      /file2,
      /file3
```

I even added `limit-severities-for-sarif: true` but that did not help.

My workflow will always fail with an error about the files I'm trying to skip.

When I change to `exit-code: '0'` then it works.
