### ISSUE TITLE
feat(input): add path to secret config file

### ISSUE THREAD

**Issue by DmitriyLewen** [aquasecurity/trivy-action#292]
## Description
Trivy has [config file](https://aquasecurity.github.io/trivy/v0.48/docs/references/configuration/config-file/) and [secret config file](https://aquasecurity.github.io/trivy/v0.48/docs/scanner/secret/#configuration), but `trivy-action` has input (`with` field) only for path to `config file`.
Is it possible to add input for path to `secret config file`?

## Related discussions
- https://github.com/aquasecurity/trivy/discussions/5824

**Comment by simar7** [comment]
We already have support for `config-file` as you mentioned. Can the path to the secret config file be specified form it? Like so:

``` yaml
secret:
  # Same as '--secret-config'
  # Default is 'trivy-secret.yaml'
  config: config/trivy/secret.yaml
```

See https://aquasecurity.github.io/trivy/v0.48/docs/references/configuration/config-file/#secret-options
