### ISSUE TITLE
Severity reported on the scan ouput and on the CVE description differ

### ISSUE THREAD

**Issue by fleroux514** [aquasecurity/trivy-action#299]
My Github action config filters on `HIGH` and `CRITICAL` severities:

```
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: rootfs
          scan-ref: /tmp/package-tmp/
          hide-progress: false
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
```

The ouput shows a High Severity CVE detection

![image](https://github.com/aquasecurity/trivy-action/assets/17277004/640f6f72-a008-41be-8454-b5b2d43f8df6)

The CVE description shows `MEDIUM` severity:  https://avd.aquasec.com/nvd/2012/cve-2012-6153/

![image](https://github.com/aquasecurity/trivy-action/assets/17277004/29b9a9a5-1095-41a6-8cee-dab0afab5018)
