### ISSUE TITLE
Trivy Action > v16.0 Fails

### ISSUE THREAD

**Issue by Bombarding** [aquasecurity/trivy-action#306]
**Issue:** Bug/Error
**Impacted Versions:** Noticed in v16.0, persists in v17.0
**Last Working Version:** v13.1
**Action Context:** https://github.com/Bombarding/build-and-publish/blob/main/.github/workflows/trivy.yml
**Failed Action Run: (v17.0)** https://github.com/Bombarding/build-and-publish/actions/runs/7845257456/job/21409285939
**Working Action Run: (v13.1):** https://github.com/Bombarding/build-and-publish/actions/runs/7845316350/job/21409463795
**Workflow Run on v17.0:**
```
Run aquasecurity/trivy-action@0.17.0
  with:
    image-ref: local-container:[2](https://github.com/Bombarding/build-and-publish/actions/runs/7845257456/job/21409285939#step:6:2)0240209141845
    scan-type: image
    hide-progress: false
    format: sarif
    output: trivy-results.sarif
    severity: CRITICAL,HIGH
    exit-code: 1
    scan-ref: .
    ignore-unfixed: false
    vuln-type: os,library
    list-all-pkgs: false
  env:
    DOCKER_NAME: local-container
    WORKING_DIRECTORY: ./Docker
/usr/bin/docker run --name acc33d223cff5a45354746a7d7a23fba099c47_12775b --label acc33d --workdir /github/workspace --rm -e "DOCKER_NAME" -e "WORKING_DIRECTORY" -e "INPUT_IMAGE-REF" -e "INPUT_SCAN-TYPE" -e "INPUT_HIDE-PROGRESS" -e "INPUT_FORMAT" -e "INPUT_OUTPUT" -e "INPUT_SEVERITY" -e "INPUT_EXIT-CODE" -e "INPUT_INPUT" -e "INPUT_SCAN-REF" -e "INPUT_IGNORE-UNFIXED" -e "INPUT_VULN-TYPE" -e "INPUT_TEMPLATE" -e "INPUT_SKIP-DIRS" -e "INPUT_SKIP-FILES" -e "INPUT_CACHE-DIR" -e "INPUT_TIMEOUT" -e "INPUT_IGNORE-POLICY" -e "INPUT_LIST-ALL-PKGS" -e "INPUT_SCANNERS" -e "INPUT_TRIVYIGNORES" -e "INPUT_ARTIFACT-TYPE" -e "INPUT_GITHUB-PAT" -e "INPUT_TRIVY-CONFIG" -e "INPUT_TF-VARS" -e "INPUT_LIMIT-SEVERITIES-FOR-SARIF" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/build-and-publish/build-and-publish":"/github/workspace" acc33d:223cff5a45354746a7d7a23fba099c47  "-a image" "-b sarif" "-c " "-d 1" "-e false" "-f os,library" "-g CRITICAL,HIGH" "-h trivy-results.sarif" "-i local-container:2024020914" "-j ." "-k " "-l " "-m " "-n " "-o " "-p false" "-q " "-r false" "-s " "-t " "-u " "-v " "-x " "-z "
Building SARIF report with options:  --exit-code  1 --vuln-type  os,library  local-container:20240209141845
```
**v17.0**
![image](https://github.com/aquasecurity/trivy-action/assets/22651146/195e8b4a-4c22-4ef7-b234-ca1b5ab93660)
![image](https://github.com/aquasecurity/trivy-action/assets/22651146/73af55b0-3899-4584-bfa2-d465feb47b7a)
**v13.1**
![image](https://github.com/aquasecurity/trivy-action/assets/22651146/845b3c67-d7d7-4474-90fc-53fe54c5f949)

**Comment by v-starodubov** [comment]
It can be related to v0.14.0 release: https://github.com/aquasecurity/trivy-action/pull/247
If you don't use parameter 'limit-severities-for-sarif' it will ignore 'severity' parameter and use 'exit-code' to signal that vulnerabilities are found.

If you want full SARIF report and fail workflow on CRITICAL,HIGH severities it won't work.

**Comment by v-starodubov** [comment]
Also, just checked v0.13.1, SARIF formar, with all severities on image that have MEDIUM cves action didn't failed at all. So i think this is why fix was applied.

**Comment by Bombarding** [comment]
@v-starodubov Thank you for the response. I think it was the `exit-code: 1` that in > v0.13.1 seems to not get the results uploaded to the github security tab.

I don't want the action to fail if it finds vulnerabilities, as I want them uploaded to Security Tab so we can ticket the items and resolve. This is ultimately what I settled on, for now, but I will still mess around with it. I have to see how `limit-severities-for-sarif: true` impacts the core repo I am working on, in relation to new findings, but the `exit-code` signifying that vulns were found now makes sense.
```yaml
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: '${{ env.DOCKER_NAME }}:${{ steps.date.outputs.date }}'
          scan-type: 'image'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: 0

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
```
![image](https://github.com/aquasecurity/trivy-action/assets/22651146/549b792e-ecb3-4587-bc42-b88697970f33)

```yaml
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: '${{ env.DOCKER_NAME }}:${{ steps.date.outputs.date }}'
          scan-type: 'image'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          limit-severities-for-sarif: true
          severity: 'CRITICAL,HIGH'
          exit-code: 0

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
```
![image](https://github.com/aquasecurity/trivy-action/assets/22651146/2a94835e-ca84-41ff-8bc9-355eab9dc690)
