### ISSUE TITLE
[bug] sarif format doesn't support "scanners" arg

### ISSUE THREAD

**Issue by antigenius0910** [aquasecurity/trivy-action#310]
Hi team, thanks for the awesome project. we follow you from tf-sec to here and would love to contribute and make this codebase as awesome as possible. 

We really want to use the sarif and codeql function so we can integrate all the GitHub code scan result to JIRA. 

when we use below setting, everything works as expected. 
```
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          hide-progress: false
          tf-vars: ${{ inputs.working-directory }}/terraform.tfvars.json
          format: table
          exit-code: 1
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM
```

result looks great vun misconfig has been found!
```
Running trivy with options: trivy config  --format table --exit-code  1 --severity  CRITICAL,HIGH,MEDIUM --tf-vars  ./terraform/terraform.tfvars.json .
Global options:  
2024-02-16T15:42:06.213Z	INFO	Misconfiguration scanning is enabled
2024-02-16T15:42:06.213Z	INFO	Need to update the built-in policies
2024-02-16T15:42:06.213Z	INFO	Downloading the built-in policies...
45.79 KiB / 45.79 KiB [-----------------------------------------------------------] 100.00% ? p/s 0s2024-02-16T15:42:07.417Z	INFO	Detected config files: 2
```

Then we switch to the format you suggested on README here https://github.com/aquasecurity/trivy-action/blob/master/README.md?plain=1#L286-L300 

```
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          tf-vars: ${{ inputs.working-directory }}/terraform.tfvars.json
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM
```

seems like nothing has been scanned 
```
Building SARIF report with options:  --exit-code  1 .
```

And we found someone report the same issue here https://github.com/aquasecurity/trivy-action/issues/301, therefore we add the scanner arg as well. 

```
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scanners: config
          hide-progress: false
          tf-vars: ${{ inputs.working-directory }}/terraform.tfvars.json
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: false
          severity: CRITICAL,HIGH,MEDIUM
```

and we are getting scanner arg is not support. 
```
Building SARIF report with options:  --exit-code  1 --scanners  config .

Scan config files for misconfigurations
2024-02-16T15:58:11.121Z	FATAL	unknown flag: --scanners

Usage:
  trivy config [flags] DIR

Aliases:
  config, conf

Scan Flags
      --file-patterns strings   specify config file patterns
      --skip-dirs strings       specify the directories or glob patterns to skip
      --skip-files strings      specify the files or glob patterns to skip

Report Flags
      --compliance string          compliance report to generate
      --exit-code int              specify exit code when any security issues are found
  -f, --format string              format (table,json,template,sarif,cyclonedx,spdx,spdx-json,github,cosign-vuln) (default "table")
      --ignore-policy string       specify the Rego file path to evaluate each vulnerability
      --ignorefile string          specify .trivyignore file (default ".trivyignore")
  -o, --output string              output file name
      --output-plugin-arg string   [EXPERIMENTAL] output plugin arguments
      --report string              specify a compliance report format for the output (all,summary) (default "all")
  -s, --severity strings           severities of security issues to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL) (default [UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL])
  -t, --template string            output template

Cache Flags
      --cache-backend string   cache backend (e.g. redis://localhost:6379) (default "fs")
      --cache-ttl duration     cache TTL when using redis as cache backend
      --clear-cache            clear image caches without scanning
      --redis-ca string        redis ca file location, if using redis as cache backend
      --redis-cert string      redis certificate file location, if using redis as cache backend
      --redis-key string       redis key file location, if using redis as cache backend
      --redis-tls              enable redis TLS with public certificates, if using redis as cache backend

Registry Flags
      --password strings        password. Comma-separated passwords allowed. TRIVY_PASSWORD should be used for security reasons.
      --registry-token string   registry token
      --username strings        username. Comma-separated usernames allowed.

Misconfiguration Flags
      --cf-params strings                 specify paths to override the CloudFormation parameters files
      --helm-set strings                  specify Helm values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --helm-set-file strings             specify Helm values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --helm-set-string strings           specify Helm string values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --helm-values strings               specify paths to override the Helm values.yaml files
      --include-non-failures              include successes and exceptions, available with '--scanners misconfig'
      --misconfig-scanners strings        comma-separated list of misconfig scanners to use for misconfiguration scanning (default [azure-arm,cloudformation,dockerfile,helm,kubernetes,terraform,terraformplan])
      --policy-bundle-repository string   OCI registry URL to retrieve policy bundle from (default "ghcr.io/aquasecurity/trivy-policies:0")
      --reset-policy-bundle               remove policy bundle
      --tf-exclude-downloaded-modules     exclude misconfigurations for downloaded terraform modules
      --tf-vars strings                   specify paths to override the Terraform tfvars files

Module Flags
      --enable-modules strings   [EXPERIMENTAL] module names to enable
      --module-dir string        specify directory to the wasm modules that will be loaded (default "/github/home/.trivy/modules")

Rego Flags
      --config-data strings         specify paths from which data for the Rego policies will be recursively loaded
      --config-policy strings       specify the paths to the Rego policy files or to the directories containing them, applying config files
      --policy-namespaces strings   Rego namespaces
      --skip-policy-update          skip fetching rego policy updates
      --trace                       enable more verbose trace output for custom queries

Kubernetes Flags
      --k8s-version string   specify k8s version to validate outdated api by it (example: 1.21.0)

Global Flags:
      --cache-dir string          cache directory (default "/github/home/.cache/trivy")
  -c, --config string             config path (default "trivy.yaml")
  -d, --debug                     debug mode
      --generate-default-config   write the default config to trivy-default.yaml
      --insecure                  allow insecure server connections
  -q, --quiet                     suppress progress bar and log output
      --timeout duration          timeout (default 5m0s)
  -v, --version                   show version
```

can you take a look on this discrepancy and point out what we might config wrongly? thanks.
