### ISSUE TITLE
Doesn't detect CVE in Dockerfile FROM imagename

### ISSUE THREAD

**Issue by d3kum1d0r1y4100** [aquasecurity/trivy-action#322]
### Description:
When the action is used with following config in github actions
```
       uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          scan-ref: '.'
          scanners: vuln,config
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'UNKNOWN,HIGH,CRITICAL'
```

and a dockerfile containing

```
FROM alpine:3.11.0
```

Trivy isn't displaying the cves present in the image name (shouldn't trivy get the imagename from it directly if we are using it in action instead of building from dockerfile and scanning that?)
