### ISSUE TITLE
Feature request: Allow for replacing FROM image in locked down environments

### ISSUE THREAD

**Issue by viper-cool79** [aquasecurity/trivy-action#333]
## Why? ##
This action is utilizing (like most I assume) a `Dockerfile` where the `FROM` points to ghcr.io. This might be blocked in certain circumstances and thus I wish for a way to input a custom image URL in a fashion similar to other settings in this action:

```YML
[...]
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          base-image: 'sub.domain.tld/namespace/trivy:0.50.1'
[...]
```

This issue comes with a suggested and ugly drafted pull request, so if someone has a better idea on how to solve this without cloning the repo and switching this one FROM on the inside please feel free to suggest solutions.
