### ISSUE TITLE
/entrypoint.sh: line 212: unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by aitrics-ray** [aquasecurity/trivy-action#343]
Hello. I added docker image scan from git action to my CI course, but sometimes I get 

```
/entrypoint.sh: line 212: unexpected EOF while looking for matching `"' 
```
error. 

```
      - name: Scan the docker that is the tag.
        if: ${{ github.ref_type == 'tag' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.environment || 'dev' }}/vc-backend:${{ needs.get-image-tag.outputs.image_tag }}
          format: 'json'
          scan-type: image
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
          output: vc-backend.json
        env:
          AWS_DEFAULT_REGION: ap-northeast-2
```
