### ISSUE TITLE
htlm template is not rendered appropriately in GHA summary

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [aquasecurity/trivy-action#361]
I am using the action as follows:

```yaml
    - name: scan the image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ inputs.image }} 
        format: template
        template: "@.github/templates/html.tpl"
        output: trivy.html
        ignore-unfixed: true
        scan-type: image
        vuln-type: 'os,library'
        severity: 'HIGH'
        exit-code: ${{ inputs.exit_code }}

  -  name: send results to job summary
      shell: bash
      if: always()
      run: cat trivy.html >> $GITHUB_STEP_SUMMARY
```

The `@.github/templates/html.tpl` is a copy paste from [this](https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl) one.

However, this is not rendered as expected in the workflow run summary as the script appears in the top of the page

starting from [this](https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl#L6) line up until [this](https://github.com/aquasecurity/trivy/blob/main/contrib/html.tpl#L82) line

I am I off in using it or is it an issue with the template?
