### ISSUE TITLE
How to clean the caches 

### ISSUE THREAD

**Issue by VictorDelCampo** [aquasecurity/trivy-action#372]
Before the last release we could reset the caches by passing an environment variable like:

```
      - name: Remove all caches and database of the trivy scanner
        uses: aquasecurity/trivy-action@d9cd5b1c23aaf8cb31bb09141028215828364bbb
        env:
          TRIVY_RESET: true
        with:
          scan-type: "image"
```

But now this --reset flag is not longer there and there is only now the utility command

`trivy clean --all`

But there is no option to pass this information as an environment variable.

How can I clean the caches using the github action? Thanks!
