### ISSUE TITLE
Trivy is failing on sarif mode

### ISSUE THREAD

**Issue by khantnaingset-kns** [aquasecurity/trivy-action#386]
I'm experiencing an issue with Trivy when running it in SARIF mode. Unfortunately, I'm not seeing any error logs, making it difficult to troubleshoot. To investigate further, I switched to Table mode, which allowed me to view more logs. The step completed successfully in Table mode, no errors logs. However, when I switched back to SARIF mode, the step failed again. I'm puzzled as to why this is happening and would appreciate an explanation.

Outputs for sarif mode:

![Screenshot 2567-09-11 at 03 17 32](https://github.com/user-attachments/assets/c1489e72-1f0e-40a2-809d-3a421f65e263)

Code for sarif mode:

![Screenshot 2567-09-11 at 03 18 41](https://github.com/user-attachments/assets/53088c63-484b-474b-b5b2-b56eec0dabe5)

Outputs for Table mode:

![image](https://github.com/user-attachments/assets/dc65351c-9abf-4c91-afa1-343c9ce9f80f)

Code for Table mode:

![image](https://github.com/user-attachments/assets/d9d8b35d-73e6-432a-aaae-c3eaaaaf2d33)

**Comment by stianfro** [comment]
I am having the same issue with a configuration like this:

```
jobs:
  trivy-analysis:
    runs-on: ubuntu-latest
      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "config"
          exit-code: "1"
          format: "sarif"
          output: "trivy-results.sarif"
```

Works when running in other formats.

**Comment by khantnaingset-kns** [comment]
> I am having the same issue with a configuration like this:
> 
> ```
> jobs:
>   trivy-analysis:
>     runs-on: ubuntu-latest
>       - name: Run Trivy
>         uses: aquasecurity/trivy-action@0.24.0
>         with:
>           scan-type: "config"
>           exit-code: "1"
>           format: "sarif"
>           output: "trivy-results.sarif"
> ```
> 
> Works when running in other formats.

Yeah, fine in other formats, error only happened in sarif mode. It's weird.

**Comment by nikpivkin** [comment]
Hi @khantnaingset-kns !

Are you encountering a issue with the latest version of action (0.26)?

**Comment by radical-izak** [comment]
This still happens in version .28

**Comment by khantnaingset-kns** [comment]
> Hi @khantnaingset-kns !
> 
> Are you encountering a issue with the latest version of action (0.26)?

Still the same on version 28.

**Comment by LukaSvastVolue** [comment]
same issue on v29

**Comment by stianfro** [comment]
Works for me since `0.28.0` with the following job:

```yaml
jobs:
  trivy-analysis:
    name: Trivy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner on built YAML files
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "config"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
          trivyignores: .trivyignore.yaml
          trivy-config: trivy.yaml
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
```

My `trivy.yaml`:

```yaml
scan:
  skip-files: []
  skip-dirs: []

severity:
  - HIGH
  - CRITICAL
```

And my `.trivyignore`:
```yaml
misconfigurations:
  - id: AVD-KSV-0011
    statement: ""
  - id: AVD-KSV-0020
    statement: ""
  - id: AVD-KSV-0021
    statement: ""
  - id: AVD-KSV-0014
    paths: []
    statement: ""
```

Note that I'm using `config` scan-type, not sure if there would be any difference with `image`.
