### ISSUE TITLE
No such image: registry.k8s.io/ingress-nginx/controller:v1.11.2

### ISSUE THREAD

**Issue by rafael-natali-bzy** [aquasecurity/trivy-action#394]
When I'm trying to scan an image from the public registry `registry.k8s.io`, the action returns: 

`unable to inspect the image (registry.k8s.io/ingress-nginx/controller:v1.11.2): Error response from daemon: No such image: registry.k8s.io/ingress-nginx/controller:v1.11.2`

Action: `aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0`

If I run Trivy outside the action I can scan the image without any problem. 

```
 - name: Run Trivy vulnerability scanner for a Docker image
          id: trivy
          uses: aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0
          with:
            image-ref: 'registry.k8s.io/ingress-nginx/controller:v1.11.2'
            format: 'json'            
            ignore-unfixed: true # ignore vulnerabilities that have no fix
            severity: 'CRITICAL,HIGH'
            scanners: 'vuln'
            output: 'trivy-results.json'
```

Any word of advise?

Thanks
