### ISSUE TITLE
fs scan error: scan error: scan failed: failed analysis: walk filesystem: walk dir error: unknown error with /github/workspace: lstat /github/workspace: no such file or directory

### ISSUE THREAD

**Issue by salmannaseempb** [aquasecurity/trivy-action#404]
There seems to be an issue with the latest release `v0.26.0` while scanning with trivy-action. 

### Expected Output:
> A successful scan

### Actual Output:
> scan error: scan failed: failed analysis: walk filesystem: walk dir error: unknown error with /github/workspace: lstat /github/workspace: no such file or directory

```
name: Run Trivy vulnerability scanner to source code
uses: aquasecurity/trivy-action@master
with:
    scan-type: fs
    scan-ref: /github/workspace/
    format: "table"
    exit-code: "0"
    ignore-unfixed: true
    vuln-type: "os,library"
    severity: "CRITICAL,HIGH"
```

> Downgrading it to `v0.23.0` still works
