### ISSUE TITLE
Trivy scan started failing recently for html format

### ISSUE THREAD

**Issue by SaurabhYadav-Savy** [aquasecurity/trivy-action#410]
Hello,
Recently trivy scan started failing for format template, specifically for html.tpl.
Few days back it was working fine.

Here is the relevant details I'm using in the workflow
```
     uses: aquasecurity/trivy-action@master
      with:
        scan-type: image
        format: 'template'
        template: '@/contrib/html.tpl'
        output: 'trivy-results.html
```

Getting error: `Fatal error	report error: unable to write results: failed to initialize template writer: error retrieving template from path: open /contrib/html.tpl: no such file or directory`
`Error: Process completed with exit code 1.`
