### ISSUE TITLE
Error while retrieving the default branch name 

### ISSUE THREAD

**Issue by BAiler-ai** [aquasecurity/trivy-action#418]
I am trying to use the latest master version (0.28.0) to scan a docker image from a private registry. We are currently on version 0.25.0
The action fails while it trys to resolve the default branch. I havn't found a flag to set the default branch for the action. I am currently testing it on a separate branch which is up-to-date with the default (master) branch. I tried to set a github-pat but it hasn't fixed it. 

The error is: 
Determining the default branch
  Retrieving the default branch name
  Not Found - https://docs.github.com/enterprise-server@3.12/rest/repos/repos#get-a-repository

**Comment by simar7** [comment]
hi @BAiler-ai trying to understand your question, how do you specify the action to use in GitHub workflow? It should be as such

```
   - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
```

That will use the released v0.28.0 version from the master branch.

**Comment by BAiler-ai** [comment]
Hi @simar7 yes very similar I just tried the @master version instead of a fixed version.

**Comment by uhei** [comment]
We have the same error. We're running
```
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repo'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'
          scanners: 'secret'
          hide-progress: true
          exit-code: '1'
```
on a Github Enterprise Server 3.13. Problem seems that the action 'actions/checkout' (which is called by 'actions/cache' which is called by 'aquasecurity/setup-trivy') is calling [Get a repository](https://docs.github.com/en/enterprise-server@3.13/rest/repos/repos?apiVersion=2022-11-28#get-a-repository).

For a 'Internal' or 'Private' repo we receive there a '404 Not found'. 

It seems that the required token is not forwarded as needed in the actions chain (just a guess).
