### ISSUE TITLE
trivyignores file not working

### ISSUE THREAD

**Issue by plumeriia** [aquasecurity/trivy-action#442]
Part of my workflow:
```
      - name: install trivy
        uses: aquasecurity/setup-trivy@v0.2.1
        with:
          version: v0.56.2

      - name: run trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.29.0
        id: trivy-check
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          exit-code: 0
          output: trivy-results.sarif
          skip-setup-trivy: true
          trivyignores: .trivyignore.yaml
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
```

`.trivyignore.yaml` **file(it is located in the / of the repository)**
```
secrets:
  - id: slack-web-hook
    paths:
      - "zaa"
  - id: github-fine-grained-pat
    paths:
      - "zaa"
```

The check sees a file containing exceptions
![image](https://github.com/user-attachments/assets/9f535605-dbdf-4d14-992b-2f5c42e5c7e6)

but `zaa` file keeps showing up in report
![image](https://github.com/user-attachments/assets/58ea3aae-4ba4-49b1-8ff9-a88dc58a194a)

I don't have such problems when running locally, the ignore file works correctly, the problems start when I try to use the action
