### ISSUE TITLE
Not usable since Ubuntu-20.04 deprecation

### ISSUE THREAD

**Issue by guimard** [aquasecurity/trivy-action#459]
This workflow is based on Ubuntu-20.04 which has been deprecated

**Comment by DmitriyLewen** [comment]
Hello @guimard 
Sorry for the delay in replying

What do you mean?
You choose the OS used in the workflow yourself.

**Comment by guimard** [comment]
I just followed your doc:

```yaml
name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
```
