### ISSUE TITLE
[GHES] trivy-action tries to resolve aquasecurity/setup-trivy with skip-setup-trivy: true

### ISSUE THREAD

**Issue by konstruktoid** [aquasecurity/trivy-action#463]
An mirrored `trivy-action` under an organization not named "aquasecurity" tries to resolve `aquasecurity/setup-trivy` even with `skip-setup-trivy: true`.

```yaml
      - name: Manual Trivy Setup
        uses: local_redacted_repository/setup-trivy@v0.2.2
        with:
          github-server-url: "https://redacted_server"

      - name: Run Trivy vulnerability scanner
        uses:  local_redacted_repository/trivy-action@0.30.0
        with:
          image-ref: 'redacted'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          skip-setup-trivy: true
````

Run log:
```console
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:a5ac7e51b41094c92402da3b24376905380afc29)
Download action repository ' local_redacted_repository/setup-trivy@v0.2.2' (SHA:ff1b8b060f23b650436d419b5e13f67f5d4c3087)
Download action repository ' local_redacted_repository/trivy-action@0.30.0' (SHA:6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5)
Getting action download info
Download action repository 'actions/cache@v4' (SHA:0c45773b623bea8c8e75f6c82b208c3cf94ea4f9)
Getting action download info
Error: Unable to resolve action `aquasecurity/setup-trivy@v0.2.2`, repository not found on this server. If you want to use this action from GitHub.com, see the following documentation: https://docs.github.com/en/enterprise/admin/github-actions/managing-access-to-actions-from-githubcom
```

**Comment by DmitriyLewen** [comment]
let's separate 2 problems:
1. setup-trivy runs install script. But this script use only `github.com` server. We will discuss about that in https://github.com/aquasecurity/trivy/discussions/8848
2. `trivy-action` from your local repository. runs `setup-trivy` even `skip-setup-trivy` flag is enable, right?
`trivy-action` check `setup-trivy` only in 1 place:
https://github.com/aquasecurity/trivy-action/blob/b3dafe507ffa004210975439a1e6156b8ebb3f50/action.yaml#L123-L133
so it looks like `skip-setup-trivy` doesn't work.
Can you look into your logs and check that `skip-setup-trivy` is really enabled?

**Comment by konstruktoid** [comment]
Using the config below, I now get `Warning: Unexpected input(s) 'github-server-url', valid inputs are ['version', 'path', 'cache', 'token']` similar to your https://github.com/DmitriyLewen/test-trivy-action/actions/runs/14970036124/job/42048691120#step:2:1.
It then times out on `Retrieving the default branch name, Connect Timeout Error`.

```yaml
      - name: Manual Trivy Setup
        uses: InternalOrg/setup-trivy@ff1b8b060f23b650436d419b5e13f67f5d4c3087
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
        with:
          github-server-url: "https://internal.example.com/"
          version: v0.62.1
```

Using the config below, I don't get that warning, but it of course fails when trying to download Trivy from GitHub. 

```yaml
      - name: Manual Trivy Setup
        uses: InternalOrg/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
        with:
          github-server-url: "https://internal.example.com/"
          version: v0.62.1
```

```sh
Run echo "installing Trivy binary"
  echo "installing Trivy binary"
  bash ./trivy/contrib/install.sh -b /run/runner/.local/bin/trivy-bin v0.62.1
  cp -r ./trivy/contrib /run/runner/.local/bin/trivy-bin/contrib
  rm -rf ./trivy
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
installing Trivy binary
aquasecurity/trivy info checking GitHub for tag 'v0.62.1'
aquasecurity/trivy crit unable to find 'v0.62.1' - use 'latest' or see https://github.com/aquasecurity/trivy/releases for details
Error: Process completed with exit code 1.
```

It never reaching the `Run Trivy vulnerability scanner` step anymore.
