### ISSUE TITLE
Issue with Trivy CI scan

### ISSUE THREAD

**Issue by ranopriyo-neogy** [aquasecurity/trivy-action#469]
I am using below in my github actions

```
name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.31.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: jamesk8s-connect
          IMAGE_TAG: ${{ github.sha }}
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          output: 'tofinalize/jamesk8s-connect-vulnerabilities.txt'
```

And the output is coming as below format without any specific CVE ID.
It used to work and suddenly stopped working. Can you please check what is missed.

```


Report Summary

┌──────────────────────────────────────────────────────────────────────────────────┬──────────┬─────────────────┬─────────┐
│                                      Target                                      │   Type   │ Vulnerabilities │ Secrets │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ 772846873375.dkr.ecr.us-east-2.amazonaws.com/jamesk8s-connect:1bc07ded59b4a12ef- │  alpine  │       29        │    -    │
│ 30445cf1491764e3b8fba38 (alpine 3.12.7)                                          │          │                 │         │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/bin/org.wso2.micro.integrator.bootstrap-4.0.0.jar   │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/bin/tcpmon-1.0.jar                                  │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/bin/tomcat-juli-9.0.34.jar                          │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/XmlSchema_1.4.7.wso2v6.jar  │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/antlr-runtime_3.2.0.wso2v1- │   jar    │        0        │    -    │
│ .jar                                                                             │          │                 │         │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/arq_1.0.0.wso2v1.jar        │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/asn-one_0.4.0.wso2v2.jar    │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/atomikos_3.8.0.wso2v1.jar   │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/axiom_1.2.11.wso2v17.jar    │   jar    │        0        │    -    │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/axis2-json_1.6.1.wso2v63.j- │   jar    │        0        │    -    │
│ ar                                                                               │          │                 │         │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤
│ home/wso2carbon/wso2mi-4.0.0/wso2/components/plugins/axis2-transport-jms_2.0.0.- │   jar    │        0        │    -    │
│ wso2v61.jar                                                                      │          │                 │         │
├──────────────────────────────────────────────────────────────────────────────────┼──────────┼─────────────────┼─────────┤

```
