### ISSUE TITLE
.trivyignore with trivy-action?

### ISSUE THREAD

**Issue by anandg112** [aquasecurity/trivy-action#52]
Does `.trivyignore` work with trivy-action out of the box? Can we put `.trivyignore` file at the root of project and Action will ignore vulnerabilities that are in the file?

**Comment by simar7** [comment]
That's an interesting idea. My guess it should work. Have you tried it?

**Comment by mgmgwi** [comment]
I tried it like this:

```
jobs:
  trivy_analysis:
    name: Trivy Analysis for slim-buster
    runs-on: "ubuntu-18.04"
    steps:
      - name: Create .trivyignore
        run: grep -Po "CVE-\d{4}-\d+" my.sarif | sort -u > .trivyignore

      - name: Run Trivy on python:3.6-slim-buster
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python:3.6-slim-buster'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-slim-buster.sarif'
          severity: 'CRITICAL,HIGH'
```

Unfortunately this does not work.
