### ISSUE TITLE
How can I send Trivy scan results to another cloud-native / open-source security product?

### ISSUE THREAD

**Issue by dshuvar** [aquasecurity/trivy-action#62]
For example, this part of code for github action send scan result to GH security tab your repo. 
```
- name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'payment-service-trivy-results.sarif'
```
How can I send Trivy scan results to another (something other than github security) cloud-native / open-source security product/panel?
