### ISSUE TITLE
Podman sock Error

### ISSUE THREAD

**Issue by Sunil-Jacob** [aquasecurity/trivy-action#67]
Hi Team,

I get the below error while using Github trivy action:

`client: no podman socket found: stat podman/podman.sock: no such file or directory`

Below is the code:
```
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'github-k8s-runner'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
```
Please advise
