### ISSUE TITLE
How to provide directory for rootfs subcommand.

### ISSUE THREAD

**Issue by rohitagg2020** [aquasecurity/trivy-action#80]
Hi,

When I do trivy rootfs -h, it says the usage will be `trivy rootfs [command options] dir`. In my local, I can give the dir. e.g. 

`trivy rootfs <GOLANG_BINARY_PATH>`

But when I am using it as github action, I am not sure how to provide this <GOLANG_BINARY_PATH>. This is my sample github action.

```
-       name: Run Trivy vulnerability scanner i repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'rootfs'
          ignore-unfixed: true
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
```

Can you please help me to figure out where I should give the path. Prior to v0.0.20, I was using input flag, but that has been removed now.

**Comment by simar7** [comment]
hi @rohitagg2020 - not sure if I understand your question. You can pass in a scan ref or an input flag as usual. https://github.com/aquasecurity/trivy-action/blob/master/action.yaml#L12-L19

**Comment by rohitagg2020** [comment]
hi @simar7 - I tried running it with both scan-ref and input, bot seems like both of them are not supported flags now. Below is the sample output I get when running trivy github action with `rootfs`.

```Running trivy with options:  --format  template --template  @/contrib/sarif.tpl --exit-code  0 --ignore-unfixed --vuln-type  os,library --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --output  trivy-results.sarif --no-progress --input ./kapp
Global options:  
Incorrect Usage: flag provided but not defined: -input

NAME:
   trivy rootfs - scan rootfs

USAGE:
   trivy rootfs [command options] dir

OPTIONS:
   --template value, -t value                     output template [$TRIVY_TEMPLATE]
2021-11-14T05:35:38.650Z	FATAL	flag provided but not defined: -input

**Comment by neil-hickey** [comment]
hi @simar7 I am also getting this:

When running:

```
- name: Run trivy
  uses: aquasecurity/trivy-action@master
  with:
    scan-type: 'rootfs'
    ignore-unfixed: true
    format: 'template'
    template: '@/contrib/sarif.tpl'
    output: 'trivy-results-binary.sarif'
    severity: 'CRITICAL,HIGH,MEDIUM'
```

The trivy binary does not get the `dir` argument (i.e `.`)

```
Running trivy with options:  --format  template --template  @/contrib/sarif.tpl --exit-code  0 --ignore-unfixed --vuln-type  os,library --severity  CRITICAL,HIGH,MEDIUM --output  trivy-results-binary.sarif --no-progress  
Global options:  
NAME:
   trivy rootfs - scan rootfs

USAGE:
   trivy rootfs [command options] dir
```
