### ISSUE TITLE
Support --list-all-pkgs option in trivy-action

### ISSUE THREAD

**Issue by m-mizutani** [aquasecurity/trivy-action#86]
Hi Team,

I want an argument to enable`--list-all-pkgs` option in trivy-action. Cloud you consider to add the option? or let me send PR.

## What I want

I would like to write config like below:

```yml
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "json"
          list-all-pkgs: true
          output: "trivy-results.json"
```

## What I got

No such option in https://github.com/aquasecurity/trivy-action/blob/master/action.yaml

## Use case

Make a decision of CI success/failure with not only vulnerability information but also package and version information. CI result can be controlled by trivy's package list and policy decision tool (e.g. OPA)
- Found malicious code is injected to OSS package, however the vulnerability is not assigned ID or not registered in Trivy DB yet for the moment
- Stop using OSS packages that own team evaluated as low quality
