### ISSUE TITLE
trivy action touches ~/.config as root

### ISSUE THREAD

**Issue by sruehl** [aquasecurity/trivy-action#90]
When using a jobs that uses a container which runs after the trivy github action you likely get a permission denied when you try to write to .config. It seems like whenever you run the trivy action the folder ends up root owned:
![image](https://user-images.githubusercontent.com/1769155/149983759-ddf8b691-f7a4-44cc-9310-a81edaaaddd2.png)

**Comment by krol3** [comment]
@sruehl could you share the steps to reproduce the issues?

**Comment by sruehl** [comment]
``` 
security_scan:
    name: Security Scan
    runs-on: [self-hosted, Linux]
    steps:      
      - name: Correct Trivy cache permissions
        run: |
          mkdir .config
          ls -la .config
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'template'
          severity: 'CRITICAL'
          cache-dir: .trivy
      - name: Correct Trivy cache permissions
        run: |
          ls -la .config
          sudo chown -R $USER:$GROUP .trivy
```
